version: 2
updates:
  - package-ecosystem: npm
    directory: "/fabrik"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/fabrik/.github/workflows"
    schedule:
      interval: monthly
